apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: YWRtaW4= #base64 encoded value admin
  username: bXlzcWwtdXNlcg== #Username-- mysql-user
  password: bXlwYXNzd29yZA== #base64 encoded values mypassword