apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: default
subjects: ## Configure all users here
- kind: ServiceAccount
  name: dev-user #"name" is case sensitive
  namespace: default
roleRef: ## Configure all User role here
  kind: Role 
  name: dev-role
  apiGroup: rbac.authorization.k8s.io
