# Docker-compose file
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pw

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root 
      DB_PASSWORD: admin 
      DB_NAME: pw
    depends_on:
      - mysql