apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  containers:
  - name: secret-container
    image: busybox
    command: ["sh","-c","echo Username: $USERNAME && echo Password $PASSWORD"]
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: config-secret
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: config-secret
            key: password
  restartPolicy: Never
